name: Applying features 
on: [push]
jobs:
  Feast-apply:
    runs-on: ubuntu-latest
    steps: 
      
    - name: Git clone our repo 
      uses: actions/checkout@v1
      with: 
        feast-version: 0.16.1
    
    - name: Start CI/CD
      run : |
        echo "Start CI/CD"
        ls -la

    - name: Start Feast apply
      run : |
        pip install feast
        feast apply  
