name: Applying features 
on: [push]
jobs:
  Feast-apply:
    runs-on: ubuntu-latest
    steps: 
      
    - name: Git clone our repo 
      uses: actions/checkout@v1
      with: 
        feast-version: 0.16.1
    
    - name: Start CI/CD
      run : |
        echo "Start CI/CD"
        ls 

    - name: Install requirements
      run : pip install -r requirements.txt 
      
    - name: Export enviroments
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region           : ${{ secrets.AWS_DEFAULT_REGION }}
      
    - name: Start Feast apply
      run : feast apply
