name: Applying features 
on: [push]
jobs:
  Feast-apply:
    runs-on: ubuntu-latest
    steps: 
      
    - name: Git clone our repo 
      uses: actions/checkout@v1
      with: 
        feast-version: 0.16.1
    
    - name: Start CI/CD
      run : |
        echo "Start CI/CD"
<<<<<<< HEAD
=======
        ls 
>>>>>>> acca9b7103f18901e03cbd2b66081954ea2f149a

    - name: Install requirements
      run : pip install -r requirements.txt 
      
    - name: Export enviroments
      run : |
        export AWS_SECRET_ACCESS_KEY=4qBhtOZHVES-3NqEe-bErGPxWaZwIrQRUUk6v9jn
        export AWS_ACCESS_KEY_ID=OGUruVnslHlArHK5aCrs
        export FEAST_S3_ENDPOINT_URL=https://storage.yandexcloud.net
        export AWS_DEFAULT_REGION=ru-central1
        feast apply
