name: Applying features 
on: [push]
jobs:
  Feast-apply:
    runs-on: ubuntu-latest
    steps: 
      
    - name: Git clone our repo 
      uses: actions/checkout@v1
      with: 
        feast-version: 0.16.1
    
    - name: Start CI/CD
      run : |
        echo "Start CI/CD"
        ls 

    - name: Install requirements
      run : pip install -r requirements.txt 
      
    - name: Start Feast apply
      run : feast apply
