name: Applying features    
on: [push]
jobs:
  Feast-apply:
    runs-on: self-hosted
    steps:          
    - name: Git clone our repo 
      uses: actions/checkout@v1

    - name: Start Feast apply
      run : sudo feast apply  
