name: Applying features 
on: [push]
jobs:
  Feast-apply:
    runs-on: self-hosted
    steps: 
    - name: Start CI/CD
      run : echo "Start CI/CD"
      
    - name: Git clone our repo 
      uses: actions/checkout@v1
        
    - name: Export enviroments
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region           : ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Start Feast apply
      run : sudo feast apply  
