name: Applying features 
env:
  AWS_SECRET_ACCESS_KEY: "4qBhtOZHVES-3NqEe-bErGPxWaZwIrQRUUk6v9jn"
  AWS_ACCESS_KEY_ID    : "OGUruVnslHlArHK5aCrs"
  FEAST_S3_ENDPOINT_URL: "https://storage.yandexcloud.net"
  AWS_DEFAULT_REGION   : "ru-central1"
  
on: [push]
jobs:
  Feast-apply:
    runs-on: self-hosted
    steps:    
    - name: Check start CI/CD
      run : echo "Start CI/CD"
      
    - name: Export enviroments
      run : |
        echo "Export enviroments"
        export AWS_SECRET_ACCESS_KEY
        export AWS_ACCESS_KEY_ID
        export FEAST_S3_ENDPOINT_URL
        export AWS_DEFAULT_REGION

    - name: Git clone our repo 
      uses: actions/checkout@v1
      
    - name: Start Feast apply
      run : |
        echo "Start applying features into Feast"
        feast apply
