name: Applying features 
env:
  AWS_SECRET_ACCESS_KEY: "4qBhtOZHVES-3NqEe-bErGPxWaZwIrQRUUk6v9jn"
  AWS_ACCESS_KEY_ID    : "OGUruVnslHlArHK5aCrs"
  FEAST_S3_ENDPOINT_URL: "https://storage.yandexcloud.net"
  AWS_DEFAULT_REGION   : "ru-central1"
  
on: [push]
jobs:
  Feast-apply:
    runs-on: self-hosted
    steps:    
    - name: Check start CI/CD
      run : echo "Start CI/CD"
      
    - name: Git clone our repo 
      uses: actions/checkout@v1
      
    - name: Export enviroments
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-access-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region           : ${{ AWS_DEFAULT_REGION }}

    - name: Start Feast apply
      run : |
        echo "Start applying features into Feast"
        feast apply
