name: Applying features
on: [push]
jobs:
  Feast-apply:
    runs-on: self-hosted
    steps:
      - run: cd /demo_feast/airflow/feast/
      - name: Check out repository code
        uses: actions/checkout@v1
      - run: feast apply
