name: Applying features 
on: [push]
jobs:
  Feast-apply:
    runs-on: ubuntu-latest
    #self-hosted
    steps:    
    - name: Check start CI/CD
      run : echo "Start CI/CD"

    - name: Start feast 
      uses: actions/checkout@v1
      
    - name: Start Feast apply
      run : |
        echo "Start applying features into Feast"
        feast apply
